return {
	"folke/which-key.nvim",
	{
		"folke/tokyonight.nvim",
		lazy = false,
		priority = 1000,
		opts = {},
	},
	"nvim-tree/nvim-tree.lua",
	'nvim-tree/nvim-web-devicons',
	"neovim/nvim-lspconfig",
	"williamboman/mason.nvim",
	"mfussenegger/nvim-lint",
	"ms-jpq/coq_nvim",
	"ms-jpq/coq.thirdparty",
	"ms-jpq/coq.artifacts",
	"romgrk/barbar.nvim",
	"zbirenbaum/copilot.lua",
	"nvim-lualine/lualine.nvim",
}
